<?php
/*
 * ____________________________________________________________
 *
 * Copyright (C) 2016 NICE IT&T
 *
 * Please do not modify this module.
 * This module may used as it is, there is no warranty.
 *
 * @ description : PHP SSL Client module.
 * @ name        : charge.php
 * @ author      : NICEPAY I&T (tech@nicepay.co.kr)
 * @ date        :
 * @ modify      : 16.05.2016
 *
 * 2016.02.22 Update Log
 * Please contact it.support@ionpay.net for inquiry
 *
 * ____________________________________________________________
 */

// Include Config File
include_once "lib/NicepayLib.php";
$nicepay = new NicepayLib();

function generateReference()
{
    $micro_date = microtime();
    $date_array = explode(" ",$micro_date);
    $date = date("YmdHis",$date_array[1]);
    $date_array[0] = preg_replace('/[^\p{L}\p{N}\s]/u', '', $date_array[0]);
    return "Ref".$date.$date_array[0].rand(100,999);
}
/*
 * ____________________________________________________________
 *
 * Virtual Account Payment Method
 * ____________________________________________________________
 */
    if(isset($_POST['payMethod'])
        && $_POST['payMethod'] == '02'
        && isset($_POST['bankCd'])
        && $_POST['bankCd']
        )
    {
        $bankCd         = $_POST['bankCd'];
        $dateNow        = date('Ymd');
        $vaExpiryDate   = date('Ymd', strtotime($dateNow . ' +1 day')); // Set VA expiry date +1 day (optional)

        // Populate Mandatory parameters to send
        $nicepay->set('iMid', 'VACCTCLOSE'); // MID for testing Close Virtual Account
        // $nicepay->set('iMid', 'VACCTOPEND'); Open Payment
        $nicepay->set('payMethod', '02');
        $nicepay->set('currency', 'IDR');
        $nicepay->set('amt', 100); // Total gross amount
        $nicepay->set('referenceNo', generateReference()); // Invoice Number or Referenc Number Generated by merchant
        $nicepay->set('description', 'Payment of Invoice No '.$nicepay->get('referenceNo')); // Transaction description
        $nicepay->set('bankCd', $bankCd);

        $nicepay->set('billingNm', 'John Doe'); // Customer name
        $nicepay->set('billingPhone', '02112345678'); // Customer phone number
        $nicepay->set('billingEmail', 'john@example.com'); //
        $nicepay->set('billingAddr', 'Jl. Jend. Sudirman No. 28');
        $nicepay->set('billingCity', 'Jakarta Pusat');
        $nicepay->set('billingState', 'DKI Jakarta');
        $nicepay->set('billingPostCd', '10210');
        $nicepay->set('billingCountry', 'Indonesia');

        $nicepay->set('deliveryNm', 'John Doe'); // Delivery name
        $nicepay->set('deliveryPhone', '02112345678');
        $nicepay->set('deliveryEmail', 'john@example.com');
        $nicepay->set('deliveryAddr', 'Jl. Jend. Sudirman No. 28');
        $nicepay->set('deliveryCity', 'Jakarta Pusat');
        $nicepay->set('deliveryState', 'DKI Jakarta');
        $nicepay->set('deliveryPostCd', '10210');
        $nicepay->set('deliveryCountry', 'Indonesia');

        $nicepay->set('vacctVaildDt', $vaExpiryDate); // Set VA expiry date example: +1 day
        $nicepay->set('vacctVaildTm', date('His')); // Set VA Expiry Time

        // Send Data
        $response = $nicepay->requestVA();


        // Response from NICEPAY
        // var_dump($response);
        if (isset($response->resultCd) && $response->resultCd == "0000") {
        echo "<pre>";
        echo "tXid              : $response->tXid\n";
        echo "callbackUrl       : $response->callbackUrl\n";
        echo "description       : $response->description\n";
        echo "payment date      : $response->transDt\n"; // YYMMDD
        echo "payment time      : $response->transTm\n"; // HH24MISS
        echo "virtual account   : $response->bankVacctNo\n";
        echo "result code       : $response->resultCd\n";
        echo "result message    : $response->resultMsg\n";
        echo "reference no      : $response->referenceNo\n";
        echo "payment method    : $response->payMethod";
        echo "</pre>";
        } elseif(isset($response->resultCd)) {
            // API data not correct or error happened in bank system, you can redirect back to checkout page or echo error message.
            // In this sample, we echo error message
            echo "<pre>";
            echo "Oops! Something happened, please notice your system administrator.\n\n";
            echo "result code       : $response->resultCd\n";
            echo "result message    : $response->resultMsg\n";
            echo "</pre>";
        } else {
            // Timeout, you can redirect back to checkout page or echo error message.
            // In this sample, we echo error message
            echo "<pre>Connection Timeout. Please Try again.</pre>";
        }

    }
/*
 * ____________________________________________________________
 *
 * Credit Card Payment Method
 * ____________________________________________________________
 */
    elseif(isset($_POST['payMethod'])
        && $_POST['payMethod'] == '01'
        && isset($_POST['billingNm'])
        && $_POST['billingNm']
        && isset($_POST['onePassToken'])
        && $_POST['onePassToken']
        )
    {

        $billingNm      = $_POST['billingNm'];
        $onePassToken   = $_POST['onePassToken'];
        $cardExpYymm    = $_POST['cardExpYymm'];
        $cardCvv        = $_POST['cardCvv'];
        $referenceNo    = $_POST['referenceNo'];

        // Populate Mandatory parameters to send
        $nicepay->set('payMethod', '01');
        $nicepay->set('currency', 'IDR');
        $nicepay->set('amt', 100); // Total gross amount
        $nicepay->set('referenceNo', $referenceNo); // Invoice Number or Reference Number Generated by merchant
        $nicepay->set('description', 'Payment of Invoice No '.$nicepay->get('referenceNo')); // Transaction description

        $nicepay->set('billingNm', 'John Doe'); // Customer name
        $nicepay->set('billingPhone', '02112345678'); // Customer phone number
        $nicepay->set('billingEmail', 'john@example.com'); //
        $nicepay->set('billingAddr', 'Jl. Jend. Sudirman No. 28');
        $nicepay->set('billingCity', 'Jakarta Pusat');
        $nicepay->set('billingState', 'DKI Jakarta');
        $nicepay->set('billingPostCd', '10210');
        $nicepay->set('billingCountry', 'Indonesia');

        $nicepay->set('deliveryNm', 'John Doe'); // Delivery name
        $nicepay->set('deliveryPhone', '02112345678');
        $nicepay->set('deliveryEmail', 'john@example.com');
        $nicepay->set('deliveryAddr', 'Jl. Jend. Sudirman No. 28');
        $nicepay->set('deliveryCity', 'Jakarta Pusat');
        $nicepay->set('deliveryState', 'DKI Jakarta');
        $nicepay->set('deliveryPostCd', '10210');
        $nicepay->set('deliveryCountry', 'Indonesia');
        $nicepay->set('onePassToken', $onePassToken);
        $nicepay->set('cardExpYymm', $cardExpYymm);
        $nicepay->set('cardCvv', $cardCvv);

        // Send Data
        $response = $nicepay->chargeCard();

        // Response from NICEPAY
//        var_dump($response);
//        exit();
        if (isset($response->resultCd) && $response->resultCd == "0000") {
            echo "<pre>";
            echo "tXid              : $response->tXid\n";
            echo "callbackUrl       : $response->callbackUrl\n";
            echo "description       : $response->description\n";
            echo "payment date      : $response->transDt\n"; // YYYYMMDD
            echo "payment time      : $response->transTm\n"; // HH24MISS
            echo "result code       : $response->resultCd\n";
            echo "result message    : $response->resultMsg\n";
            echo "reference no      : $response->referenceNo\n";
            echo "payment method    : $response->payMethod\n";
            echo "recurring token   : $response->recurringToken";
            echo "</pre>";
            // var_dump($response);
        } elseif(isset($response->resultCd)) {
            // API data not correct or error happened in bank system, you can redirect back to checkout page or echo error message.
            // In this sample, we echo error message
            echo "<pre>";
            echo "Oops! Something happened, please notice your system administrator.\n\n";
            echo "result code       : $response->resultCd\n";
            echo "result message    : $response->resultMsg\n";
            echo "</pre>";
        } else {
            // Timeout, you can redirect back to checkout page or echo error message.
            // In this sample, we echo error message
            echo "<pre>Connection Timeout. Please Try again.</pre>";
        }
    }
    elseif(isset($_POST['payMethod']) && $_POST['payMethod'] == '03' &&
                    isset($_POST['recurringKeyIn']) && $_POST['recurringKeyIn']) {

            // Populate Mandatory parameters to send
            $nicepay->set('payMethod', '01');
            $nicepay->set('currency', 'IDR');
            // Total gross amount
            $nicepay->set('amt', 100);
            // Invoice Number or Referenc Number Generated by merchant
            $nicepay->set('referenceNo', generateReference());
            // Transaction description
            $nicepay->set('description', 'Payment of Invoice No '.$nicepay->get('referenceNo'));

            // Customer name
            $nicepay->set('billingNm', 'John Doe');
            // Customer phone number
            $nicepay->set('billingPhone', '02112345678');
            // Customer email
            $nicepay->set('billingEmail', 'john@example.com');
            $nicepay->set('billingAddr', 'Jl. Jend. Sudirman No. 28');
            $nicepay->set('billingCity', 'Jakarta Pusat');
            $nicepay->set('billingState', 'DKI Jakarta');
            $nicepay->set('billingPostCd', '10210');
            $nicepay->set('billingCountry', 'Indonesia');

            // Delivery name
            $nicepay->set('deliveryNm', 'John Doe');
            $nicepay->set('deliveryPhone', '02112345678');
            $nicepay->set('deliveryEmail', 'john@example.com');
            $nicepay->set('deliveryAddr', 'Jl. Jend. Sudirman No. 28');
            $nicepay->set('deliveryCity', 'Jakarta Pusat');
            $nicepay->set('deliveryState', 'DKI Jakarta');
            $nicepay->set('deliveryPostCd', '10210');
            $nicepay->set('deliveryCountry', 'Indonesia');
            $nicepay->set('recurringToken', $_POST['recurringKeyIn']);
            $nicepay->set('cardCvv', '');

            // Send Data
            $response = $nicepay->requestRecurring();

            // Response from NICEPAY
            // var_dump($response);
            // exit();
            if (isset($response->resultCd) && $response->resultCd == "0000") {
                echo "<pre>";
                echo "tXid            : $response->tXid\n";
                echo "callbackUrl     : $response->callbackUrl\n";
                echo "description     : $response->description\n";
                echo "payment date    : $response->transDt\n";
                echo "payment time    : $response->transTm\n";
                echo "result code     : $response->resultCd\n";
                echo "result message  : $response->resultMsg\n";
                echo "reference no    : $response->referenceNo\n";
                echo "payment method  : $response->payMethod";
                echo "</pre>";
            } elseif(isset($response->resultCd)) {
                // API data not correct or error happened in bank system, you can redirect back to checkout page or echo error message.
                // In this sample, we echo error message
                // header("Location: "."http://example.com/checkout.php");
                echo "<pre>";
                echo "result code       : ".$response->resultCd."\n";
                echo "result message    : ".$response->resultMsg."\n";
                // echo "requestUrl        : ".$response->data->requestURL."\n";
                echo "</pre>";
            } else {
                // Timeout, you can redirect back to checkout page or echo error message.
                // In this sample, we echo error message
                // header("Location: "."http://example.com/checkout.php");
                echo "<pre>Connection Timeout. Please Try again.</pre>";
            }

        } elseif(    isset($_POST['payMethod']) && $_POST['payMethod'] == '04' &&
                    isset($_POST['recurringThreeDS']) && $_POST['recurringThreeDS'] &&
                    isset($_POST['cvvThreeDS']) && $_POST['cvvThreeDS'] ) {

            // Populate Mandatory parameters to send
            $nicepay->set('payMethod', '01');
            $nicepay->set('currency', 'IDR');
            // Total gross amount
            $nicepay->set('amt', 100);
            // Invoice Number or Referenc Number Generated by merchant
            $nicepay->set('referenceNo', generateReference());
            // Transaction description
            $nicepay->set('description', 'Payment of Invoice No '.$nicepay->get('referenceNo'));

            // Customer name
            $nicepay->set('billingNm', 'John Doe');
            // Customer phone number
            $nicepay->set('billingPhone', '02112345678');
            // Customer email
            $nicepay->set('billingEmail', 'john@example.com');
            $nicepay->set('billingAddr', 'Jl. Jend. Sudirman No. 28');
            $nicepay->set('billingCity', 'Jakarta Pusat');
            $nicepay->set('billingState', 'DKI Jakarta');
            $nicepay->set('billingPostCd', '10210');
            $nicepay->set('billingCountry', 'Indonesia');

            // Delivery name
            $nicepay->set('deliveryNm', 'John Doe');
            $nicepay->set('deliveryPhone', '02112345678');
            $nicepay->set('deliveryEmail', 'john@example.com');
            $nicepay->set('deliveryAddr', 'Jl. Jend. Sudirman No. 28');
            $nicepay->set('deliveryCity', 'Jakarta Pusat');
            $nicepay->set('deliveryState', 'DKI Jakarta');
            $nicepay->set('deliveryPostCd', '10210');
            $nicepay->set('deliveryCountry', 'Indonesia');
            $nicepay->set('recurringToken', $_POST['recurringThreeDS']);
            $nicepay->set('cardCvv', $_POST['cvvThreeDS']);

            // Send Data
            $response = $nicepay->requestRecurring();

            // Response from NICEPAY
            // var_dump($response);
            // exit();
            if (isset($response->resultCd) && $response->resultCd == "0000") {
                echo "<pre>";
                echo "tXid            : $response->tXid\n";
                echo "callbackUrl     : $response->callbackUrl\n";
                echo "description     : $response->description\n";
                echo "payment date    : $response->transDt\n";
                echo "payment time    : $response->transTm\n";
                echo "result code     : $response->resultCd\n";
                echo "result message  : $response->resultMsg\n";
                echo "reference no    : $response->referenceNo\n";
                echo "payment method  : $response->payMethod";
                echo "</pre>";
            } elseif(isset($response->resultCd)) {
                // API data not correct or error happened in bank system, you can redirect back to checkout page or echo error message.
                // In this sample, we echo error message
                // header("Location: "."http://example.com/checkout.php");
                echo "<pre>";
                echo "result code       : ".$response->resultCd."\n";
                echo "result message    : ".$response->resultMsg."\n";
                // echo "requestUrl        : ".$response->data->requestURL."\n";
                echo "</pre>";
            } else {
                // Timeout, you can redirect back to checkout page or echo error message.
                // In this sample, we echo error message
                // header("Location: "."http://example.com/checkout.php");
                echo "<pre>Connection Timeout. Please Try again.</pre>";
            }
        }
    // Unknown
    else {
        echo "Unknown method";
    }
