<?php
/*
 * ____________________________________________________________
 *
 * Copyright (C) 2016 NICE IT&T
 *
 * Please do not modify this module.
 * This module may used as it is, there is no warranty.
 *
 * @ description : PHP SSL Client module.
 * @ name        : NicepayLite.php
 * @ author      : NICEPAY I&T (tech@nicepay.co.kr)
 * @ date        :
 * @ modify      : 09.03.2016
 *
 * 09.03.2016 Update Log
 * Please contact it.support@ionpay.net for inquiry
 *
 * ____________________________________________________________
 */

// Include Config File
include_once "lib/NicepayLib.php";
$nicepay = new NicepayLib();

function generateReference()
{
    $micro_date = microtime();
    $date_array = explode(" ",$micro_date);
    $date = date("YmdHis",$date_array[1]);
    $date_array[0] = preg_replace('/[^\p{L}\p{N}\s]/u', '', $date_array[0]);
    return "Ref".$date.$date_array[0].rand(100,999);
}
/*
 * ____________________________________________________________
 *
 * Virtual Account Payment Method
 * ____________________________________________________________
 */
    if(isset($_POST['payMethod'])
        && $_POST['payMethod'] == '02'
        && isset($_POST['bankCd'])
        && $_POST['bankCd']
        )
    {
        $bankCd         = $_POST['bankCd'];
        $dateNow        = date('Ymd');
        $vaExpiryDate   = date('Ymd', strtotime($dateNow . ' +1 day')); // Set VA expiry date +1 day (optional)

        // Populate Mandatory parameters to send
        $nicepay->set('payMethod', '02');
        $nicepay->set('currency', 'IDR');
        $nicepay->set('amt', 12000); // Total gross amount
        $nicepay->set('referenceNo', generateReference()); // Invoice Number or Referenc Number Generated by merchant
        $nicepay->set('description', 'Payment of Invoice No '.$nicepay->get('referenceNo')); // Transaction description
        $nicepay->set('bankCd', $bankCd);

        $nicepay->set('billingNm', 'John Doe'); // Customer name
        $nicepay->set('billingPhone', '02112345678'); // Customer phone number
        $nicepay->set('billingEmail', 'john@example.com'); //
        $nicepay->set('billingAddr', 'Jl. Jend. Sudirman No. 28');
        $nicepay->set('billingCity', 'Jakarta Pusat');
        $nicepay->set('billingState', 'DKI Jakarta');
        $nicepay->set('billingPostCd', '10210');
        $nicepay->set('billingCountry', 'Indonesia');

        $nicepay->set('deliveryNm', 'John Doe'); // Delivery name
        $nicepay->set('deliveryPhone', '02112345678');
        $nicepay->set('deliveryEmail', 'john@example.com');
        $nicepay->set('deliveryAddr', 'Jl. Jend. Sudirman No. 28');
        $nicepay->set('deliveryCity', 'Jakarta Pusat');
        $nicepay->set('deliveryState', 'DKI Jakarta');
        $nicepay->set('deliveryPostCd', '10210');
        $nicepay->set('deliveryCountry', 'Indonesia');

        $nicepay->set('vacctValidDt', $vaExpiryDate); // Set VA expiry date example: +1 day
        $nicepay->set('vacctValidTm', date('His')); // Set VA Expiry Time

        // Send Data
//        var_dump($nicepay->requestData);
        $response = $nicepay->requestVA();

//        var_dump($response);
//        exit();
        // Response from NICEPAY

        if (isset($response->resultCd) && $response->resultCd == "0000") {
        echo "<pre>";
        echo "tXid              : $response->tXid (Save to your database to check status) \n";
        echo "callbackUrl       : $response->callbackUrl\n";
        echo "description       : $response->description\n";
        echo "payment date      : $response->transDt\n"; // YYMMDD
        echo "payment time      : $response->transTm\n"; // HH24MISS
        echo "virtual account   : $response->bankVacctNo (For customer to transfer) \n";
        echo "result code       : $response->resultCd\n";
        echo "result message    : $response->resultMsg\n";
        echo "reference no      : $response->referenceNo\n";
        echo "payment method    : $response->payMethod";
        echo "</pre>";
        } elseif(isset($response->resultCd)) {
            // API data not correct, you can redirect back to checkout page or echo error message.
            // In this sample, we echo error message
            echo "<pre>";
            echo "result code       :".$response->resultCd."\n";
            echo "result message    :".$response->resultMsg."\n";
            echo "</pre>";
        } else {
            // Timeout, you can redirect back to checkout page or echo error message.
            // In this sample, we echo error message
            echo "<pre>Connection Timeout. Please Try again.</pre>";
        }

    }
/*
 * ____________________________________________________________
 *
 * Credit Card Payment Method
 * ____________________________________________________________
 */
    elseif(isset($_POST['payMethod'])
        && $_POST['payMethod'] == '01'
        )
    {

        // Populate Mandatory parameters to send
        $nicepay->set('payMethod', '01');
        $nicepay->set('currency', 'IDR');
        $nicepay->set('amt', 1000); // Total gross amount
        $nicepay->set('referenceNo', generateReference()); // Invoice Number or Referenc Number Generated by merchant
        $nicepay->set('description', 'Payment of Invoice No '.$nicepay->get('referenceNo')); // Transaction description

        $nicepay->set('billingNm', 'John Doe'); // Customer name
        $nicepay->set('billingPhone', '02112345678'); // Customer phone number
        $nicepay->set('billingEmail', 'john@example.com'); //
        $nicepay->set('billingAddr', 'Jl. Jend. Sudirman No. 28');
        $nicepay->set('billingCity', 'Jakarta Pusat');
        $nicepay->set('billingState', 'DKI Jakarta');
        $nicepay->set('billingPostCd', '10210');
        $nicepay->set('billingCountry', 'Indonesia');

        $nicepay->set('deliveryNm', 'John Doe'); // Delivery name
        $nicepay->set('deliveryPhone', '02112345678');
        $nicepay->set('deliveryEmail', 'john@example.com');
        $nicepay->set('deliveryAddr', 'Jl. Jend. Sudirman No. 28');
        $nicepay->set('deliveryCity', 'Jakarta Pusat');
        $nicepay->set('deliveryState', 'DKI Jakarta');
        $nicepay->set('deliveryPostCd', '10210');
        $nicepay->set('deliveryCountry', 'Indonesia');

        // Send Data
        $response = $nicepay->chargeCard();


        // Response from NICEPAY
//        var_dump($response);
//        exit();
        if (isset($response->data->resultCd) && $response->data->resultCd == "0000") {
              header("Location: ".$response->data->requestURL."?tXid=".$response->tXid);
//            please save tXid in your database
//            echo "<pre>";
//            echo "tXid              : $response->tXid\n";
//            echo "API Type          : $response->apiType\n";
//            echo "Request Date      : $response->requestDate\n";
//            echo "Response Date     : $response->requestDate\n";
//            echo "</pre>";
        } elseif(isset($response->data->resultCd)) {
            // API data not correct or error happened in bank system, you can redirect back to checkout page or echo error message.
            // In this sample, we echo error message
            // header("Location: "."http://example.com/checkout.php");
            echo "<pre>";
            echo "result code       : ".$response->data->resultCd."\n";
            echo "result message    : ".$response->data->resultMsg."\n";
//            echo "requestUrl        : ".$response->data->requestURL."\n";
            echo "</pre>";
        } else {
            // Timeout, you can redirect back to checkout page or echo error message.
            // In this sample, we echo error message
            // header("Location: "."http://example.com/checkout.php");
            echo "<pre>Connection Timeout. Please Try again.</pre>";
        }
    }

    // Unknown
    else {
        echo "Unknown method";
    }
